
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: ng build --prod --output-hashing=all
      - name: Cache artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.ref }}
          restore-keys: |
            ${{ github.ref }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.ref }}
      - name: Run tests
        run: ng test --progress false --watch false
